# Generated by Django 5.0.6 on 2024-06-13 19:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Kategorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(max_length=200)),
                (
                    "created_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("published_date", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Klient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nabywca", models.CharField(default="---", max_length=200)),
                ("ulica", models.CharField(default="---", max_length=200)),
                ("miasto", models.CharField(default="---", max_length=200)),
                ("nrTel", models.CharField(default="---", max_length=200)),
                ("Email", models.CharField(default="---", max_length=200)),
                ("NIP", models.CharField(default="---", max_length=200)),
                (
                    "rabat",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "created_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("published_date", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Pracownik",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sprzedawca", models.CharField(default="---", max_length=200)),
                ("pracownik", models.CharField(default="---", max_length=200)),
                ("ulica", models.CharField(default="---", max_length=200)),
                ("miasto", models.CharField(default="---", max_length=200)),
                ("nrTel", models.CharField(default="---", max_length=200)),
                ("Email", models.CharField(default="---", max_length=200)),
                ("NIP", models.CharField(default="---", max_length=200)),
                ("nrKonta", models.CharField(default="---", max_length=200)),
                (
                    "created_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("published_date", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Start",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=70, null=True)),
                (
                    "description",
                    models.TextField(blank=True, max_length=1024, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Faktura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("published_date", models.DateTimeField(blank=True, null=True)),
                (
                    "nabywca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="inser.klient"
                    ),
                ),
                (
                    "sprzedawca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inser.pracownik",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Usluga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(default="---", max_length=200)),
                ("jednostka", models.CharField(max_length=200)),
                (
                    "cena_netto",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "stawka_VAT",
                    models.PositiveIntegerField(blank=True, default=23, null=True),
                ),
                (
                    "created_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("published_date", models.DateTimeField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inser.kategorie",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FakturaUsluga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ilosc", models.PositiveIntegerField(default=1)),
                (
                    "faktura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="inser.faktura"
                    ),
                ),
                (
                    "usluga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="inser.usluga"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="faktura",
            name="produkty",
            field=models.ManyToManyField(related_name="faktury", to="inser.usluga"),
        ),
    ]
